name: Build and Deploy to Github pages

on:
#  release:
#    types: [created]
  push:
    branches: [ master ]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm run deploy
